### ISSUE TITLE
新功能，网络爬图获取图片时，新增一个浮动框显示爬图状态，每1秒或2秒更新一次

### ISSUE THREAD

**Issue by arlose** [blastZ/easy-tag#9]
接口/api/getscrapystat，参数usrname和taskname，GET

**Comment by blastZ** [comment]
@arlose  这是指爬完前不能操作，还是说只是显示下爬取状态？

**Comment by arlose** [comment]
显示爬取状态，点击爬取图片后，每隔一两秒调用一次该接口，显示为一个状态项，爬取结束后状态显示关闭
爬取图片时还可以进行其他操作

**Comment by arlose** [comment]
已完成
